### ISSUE TITLE
Crashing at "Compute PIV"

### ISSUE THREAD

**Issue by jack-elliott** [mI-PIV/app#112]
V0.16 is crashing on multiple phones at the "Compute PIV" step. Videos are not high res.

**Comment by kp-121** [comment]
Can you get me which Android SDK these phones are using (Settings > About Device) ? I have an idea what it could be but I need to know for sure.

**Comment by kp-121** [comment]
Android 11 [no longer](https://developer.android.com/about/versions/11/privacy/storage) let's us use the user's Pictures directory to save data, this was causing a crash when trying to write data files to the user's phone. This is also why only the Base image was being saved to experiment directory. I'll start looking into where we can save data and make the needed changes.

**Comment by kp-121** [comment]
#115 should fix any Android 11, and Android 7.1.1 compatibility issues. @jack-elliott I'll create a release (v0.16a) tomorrow that can be tested. I'll keep this issue opened until I hear back that everything is working.
