### ISSUE TITLE
App-wide feedback suggestions

### ISSUE THREAD

**Issue by kp-121** [mI-PIV/app#122]
- [ ] Color-coded sections
- [ ] Sections based on knowledge level (high school/intermediate - undergrad/advanced)
- [ ] Start/Stop animation buttons color change 
- [x] After frame extraction, either tell the user to go back, or automatically return to the experiments
- [ ] 'About' page describing vision and goal of the app, version number, etc.
- [ ] Reorder fluids glossary (alphabetical, tree-structured topics)
- [ ] A more detailed explanation for the video tutorials
- [ ] "Try these experiments" on the home page
- [ ] Simplified content for younger students

**Comment by kp-121** [comment]
#133 The app now automatically returns to the experiment menu after frame extraction

**Comment by jack-elliott** [comment]
Removing this and moving it to the desired features excel file. Will open specific issues separately when we have actionable requests.
