### ISSUE TITLE
PPR Map

### ISSUE THREAD

**Issue by kp-121** [mI-PIV/app#128]
We can add the magnitude and ppr to the info section. The more information delivered to the user the better.

**Comment by jack-elliott** [comment]
And in this, we'll remove the single-pass, and replacement results from the display, and also truncate the results shown to 2 decimal places.

**Comment by kp-121** [comment]
- [ ] Add PPR to PivResultData class
This is for me.

**Comment by jack-elliott** [comment]
Keeping this, it will be good to show people where they have noise in their images
