### ISSUE TITLE
Red/Blue Vorticity Colormap

### ISSUE THREAD

**Issue by jack-elliott** [mI-PIV/app#130]
To make the vorticity easier to understand and align with a common practice, we should have a red (darkest red=most positive) to blue (darkest blue=most negative) colormap for the vorticity, with fully transparent as the 0 value. Example image is attached. 
![VorticityExample](https://user-images.githubusercontent.com/77805273/122799343-d703e100-d27e-11eb-9f19-0f1cda5e36ea.PNG)

**Comment by kp-121** [comment]
#140 Adds a red/blue vorticity map, and the results page defaults to it.
