### ISSUE TITLE
Spatial Data in Results Info section

### ISSUE THREAD

**Issue by kp-121** [mI-PIV/app#141]
Display spatial measurements in the results info section when a successful spatial calibration has happened.

**Comment by jack-elliott** [comment]
isn't this complete?

**Comment by kp-121** [comment]
Yes it is, we can always open it back up if any problems arise.

**Comment by jack-elliott** [comment]
Sounds good, I did notice that the framerate isn't accounted for, and
displacements are still in pixels only. Are we able to pull in framerate
from the video and add it so the final output is m/s?

**Comment by kp-121** [comment]
Ah, if we're not seeing physical displacements then this still needs to be implemented. I'll open it back up.

**Comment by kp-121** [comment]
Yep, we can pull the framerate from videos and use them in with our calibration calculations.

**Comment by jack-elliott** [comment]
to clarify, time isn't being displayed on the results page>information, I
don't know whether the framerate is or is not part of the calibration.

**Comment by kp-121** [comment]
see #217
