### ISSUE TITLE
Replacement and Multi-Pass only Zeros

### ISSUE THREAD

**Issue by jack-elliott** [mI-PIV/app#145]
Only the single pass option is providing any non-zero vectors. The multi-pass and replacement options are empty (vector plot results, vorticity, and interactive display).

**Comment by kp-121** [comment]
The primary peak removal algorithm that I just put into place was buggy. I have fixed it, but it adds a lot of time to the PIV calculation. This issue is fixed, but I'm going to add a new ticket to speed up the primary peak removal algorithm.
