### ISSUE TITLE
Raw Image Background Issue

### ISSUE THREAD

**Issue by jack-elliott** [mI-PIV/app#147]
When in the results page, selecting the raw image background and then apply changes returns the user to login at start an experiment page.

**Comment by kp-121** [comment]
I wasn't able to replicate this bug. Is this happening from a loaded experiment or a new experiment?

**Comment by jack-elliott** [comment]
A new experiment, and on the current version rather than take the user to the login, if I select raw image, then apply changes, then select another color background, it takes the user to the select images screen (Google Pixel4). I can Zoom if the problem still isn't showing up on your end.

**Comment by kp-121** [comment]
Whenever the app kicks you to the main menu or the experiment menu, that usually means there was a crash. There was a bug in the color picker that I noticed with the arrow color picker and I fixed it yesterday. This bug would've caused a crash with the background solid color picker as well. It sounds like that is what is happening here. I'll leave this open until we can confirm this was the culprit.

**Comment by jack-elliott** [comment]
Sounds good, I'll make sure to test this shortly and see if it is fixed
