### ISSUE TITLE
Primary Peak removal optimization

### ISSUE THREAD

**Issue by kp-121** [mI-PIV/app#149]
The new primary peak removal algorithm is slow and needs to be optimized.

**Comment by jack-elliott** [comment]
Is the 2D box method any faster?

**Comment by kp-121** [comment]
It should be. I'll have to revisit these peak removal methods again and do some quick testing to see which are faster. I'll update here when I have some definitive answers.

**Comment by jack-elliott** [comment]
Ok, I know it removes corners for the sake of time, but there may be some workarounds for that if necessary (e.g., an elliptic region removal). The deblur image generator makes a good testing ground for these.

**Comment by kp-121** [comment]
The 2D box method is exponentially faster. I'll go ahead and implement that right now so it's in tomorrow's release.

**Comment by jack-elliott** [comment]
Sounds good. We can check the efficacy of that later, but I don't think it's going to be terrible.
