### ISSUE TITLE
Multi-Pass Problem

### ISSUE THREAD

**Issue by jack-elliott** [mI-PIV/app#158]
Multi-Pass is not working correctly. Photos below show a first pass (looks correct) and second pass (regions around the vortex ring edge are visibly smaller than would be correct). I have tried changing the post-processing parameters, window size, etc. to fix this and this occurs every time. Not really sure what's happening here but I would be happy to discuss while looking at code if that could help. My best guess (emphasis on guess) is that the second pass results are not being correctly added to the offset values from the first pass
![SinglePass](https://user-images.githubusercontent.com/77805273/134735827-168a9375-e3c6-42b3-99f9-c56bf97a0cbf.PNG)
?
![Multi-Pass](https://user-images.githubusercontent.com/77805273/134735842-a17cb579-fd72-444c-8650-e0e2713ee444.PNG)

**Comment by kp-121** [comment]
Hey @jack-elliott I've added 1 to the new displacement, and the results look a lot better. I'm not sure how I can tell if it is completely fixed. I'll add a few experiments and let you decide. We can always release with the changes and let you test it more as well.

![old_multipass](https://user-images.githubusercontent.com/20914336/140621058-fc7d0661-c177-4484-aac7-c0ffa0b0afde.png)

![new_multipass](https://user-images.githubusercontent.com/20914336/140621061-3bb67f18-efed-4432-ad61-30f13da9781c.png)

**Comment by kp-121** [comment]
Single pass
![7S](https://user-images.githubusercontent.com/20914336/140621424-c50c9cd3-310d-4eed-b6bf-daf2eb2bb4de.png)

Multi pass
![7M](https://user-images.githubusercontent.com/20914336/140621429-bb1050e6-d11f-41c5-889d-572b90c30cf9.png)

**Comment by kp-121** [comment]
singlepass
![8S](https://user-images.githubusercontent.com/20914336/140621447-56f2be4b-546a-4efb-8b00-505661b629ea.png)

multipass
![8M](https://user-images.githubusercontent.com/20914336/140621449-7c9a12f9-e36b-47bd-856a-4fc8ac5cbde4.png)

**Comment by kp-121** [comment]
singlepass
![10S](https://user-images.githubusercontent.com/20914336/140621461-6ae65378-bb7a-48e5-a6a2-67dfabd4eba8.png)

multipass
![10M](https://user-images.githubusercontent.com/20914336/140621463-b781126d-023f-40a2-800a-db4109d25c63.png)

**Comment by jack-elliott** [comment]
I think as long as they look good for now our purpose is served (for Beta), the best way to test if this is actually correct is going to be to run the current processing on the uniform shear synthetic images (MATLAB generated) and see if the results are correct. I'll email the Box link to those images, hopefully those images and the processing are still wrapped?

**Comment by kp-121** [comment]
Sounds good, I'll release these changes and then we can continue testing for later releases.
