### ISSUE TITLE
Negative Image Filter

### ISSUE THREAD

**Issue by jack-elliott** [mI-PIV/app#159]
Low priority, but the ability to pre-process the images through a negative filter would let users take video of dark objects on a light background (pepper flakes on the surface of water in a paper plate) would allow creative user opportunities and circumvent the whole laser issue.

**Comment by kp-121** [comment]
![GrayFrame1_neg__Experiment_52](https://user-images.githubusercontent.com/20914336/178792799-1eccff13-cffd-42ae-a2db-64bb8cc190e1.png)
