### ISSUE TITLE
Frame Set Background

### ISSUE THREAD

**Issue by jack-elliott** [mI-PIV/app#186]
Frame Set background is resulting in near zero value vectors everywhere in the image.

**Comment by jack-elliott** [comment]
Also, the "View Background" option disappears almost immediately

**Comment by kp-121** [comment]
Is this in both the PIV and frame extraction page?

**Comment by jack-elliott** [comment]
Extraction page is where I came across the inabili9ty to see the generated background, The frame set resulting in zero value vectors everywhere is in PIV results. Sorry, I probably should have opened two issues.

**Comment by kp-121** [comment]
That's okay. I was just wondering where to start looking. If it isn't an easy fix, I'll probably open a second ticket.

**Comment by kp-121** [comment]
Is the "View Background" checkbox disappearing or the view background popup disappearing?

**Comment by jack-elliott** [comment]
The view background popup is not appearing with the view background checkbox selected

**Comment by kp-121** [comment]
#192 fixes background preview popup issue
