### ISSUE TITLE
U and V in Results

### ISSUE THREAD

**Issue by jack-elliott** [mI-PIV/app#187]
In the interactive results page, the U and V vectors are incorrect: i.e., the V is giving positive values when looking at the display the results should clearly be negative.

**Comment by kp-121** [comment]
Are there any negative values in the results page for vectors? I'm wondering when we convert the value to a string, if we're not converting the negative sign with it.

**Comment by jack-elliott** [comment]
It looks like they simply aren't flipped (in the Y direction) actually, so
this is probably an easier fix than what I thought.

**Comment by kp-121** [comment]
#192 fixes this
