### ISSUE TITLE
Lock Screen Rotation

### ISSUE THREAD

**Issue by kp-121** [mI-PIV/app#191]
We'll need to lock the screen rotation for menu screens.

**Comment by kp-121** [comment]
@Kevin-Jay-Roberts21 Each of our activities that has menus need to be locked in portrait orientation. You'll just need to add the setRequestedOrientation line to the activity's onCreateView, onResume, and onPause methods. If the activity doesn't have the method then you can just add them. See the CameraFragment.java example below.

![image](https://user-images.githubusercontent.com/20914336/141364221-aaf5fd69-fb03-4e36-9cb4-d9f4c808ce92.png)

**Comment by Kevin-Jay-Roberts21** [comment]
Will we be doing this everywhere in the app? For example, will the results
page also be locked? Also, this means that there will be no need to
add scrollability correct? Since we're not allowing the user to rotate the
screen anyway?

**Comment by kp-121** [comment]
Each of the activities that has a menu. The results page doesn't have a menu. This is a work-around because of the issue of scrollable layouts.

**Comment by Kevin-Jay-Roberts21** [comment]
Sounds good. I'll get to it!

**Comment by Kevin-Jay-Roberts21** [comment]
Have you added the change in CameraFragment.java in the scrollable_layouts branch? I did a fetch but I'm not seeing any changes.

**Comment by kp-121** [comment]
It has already been merged to main. You need to pull main into your branch.

**Comment by Kevin-Jay-Roberts21** [comment]
Got it. Thanks.

**Comment by Kevin-Jay-Roberts21** [comment]
How can a tell if a .java file has a menu? I guess what does it mean for an activity to have a menu? Thanks.

**Comment by kp-121** [comment]
Forget menus. If you can rotate the screen to landscape mode and any of the layout is cut-off then the layout will need to be locked.

**Comment by Kevin-Jay-Roberts21** [comment]
Cool. Thanks again!

**Comment by Kevin-Jay-Roberts21** [comment]
I just updated the HomeActivity.java file in the scrollable_layouts branch, locking the screen. Would you be willing to take a look at it? Will that work? I decided to lock the screen in this layout because in landscape mode, the picture blocks the buttons. Thanks.

**Comment by Kevin-Jay-Roberts21** [comment]
Commit 6daa220 fixes this issue.

**Comment by kp-121** [comment]
#198
