### ISSUE TITLE
Frame Generated Popup

### ISSUE THREAD

**Issue by jack-elliott** [mI-PIV/app#195]
We should have a pop-up after frame generation (and background preview if selected) which tells the user the frame generation is complete, the name of the resulting frame set (i.e., Set 1 for the first time) and then to go to the "Select Images for PIV".  Honestly, it might instead be best if we just take the user straight to "frame Selection" with the image set they just generated selected.  Thoughts?

**Comment by kp-121** [comment]
I like both the ideas, and it would be a quick task to implement.

**Comment by jack-elliott** [comment]
If it would be quick, let's do the second, where we take them straight to selecting the specific images from that frame set

**Comment by jack-elliott** [comment]
When we do this, right after frames are generated and the set number pops up, can we let the user select from: Head to processing OR continue generating frames?
