### ISSUE TITLE
Particle Density Preview Addition

### ISSUE THREAD

**Issue by jack-elliott** [mI-PIV/app#196]
The preview looks great! Can we add this text:

- [x] Add text:
if no: try a larger window size,
if yes but there are more than 15: try a smaller window
Yes, and I can see how much they moved between the two frames: choose the window size in the next step!

- [x] Under the preview and before the radio buttons/headers, can we add the label: "Window Size:"
- [x] Let's remove the "Yes" and "No" from the bottom and just have an OK.

- [x] Fix smoothing

**Comment by jack-elliott** [comment]
Also, are we up sampling then smoothing these preview images? the 32x32 doesn't look as grainy as I would expect. If we are, can we remove that? The visible pixellated-ness of these image interrogation regions is good and should remain I think.

**Comment by kp-121** [comment]
We aren't doing any upsampling or smoothing directly, but I'll check if any of the helper functions I use does it.
