### ISSUE TITLE
Stuck on Single Pass Processing

### ISSUE THREAD

**Issue by jack-elliott** [mI-PIV/app#197]
(Samsung Galaxy A51) when I run an image pair using default or otherwise parameters, the background subtraction works, but the "Calculating single-pass PIV" message persists for as long as I have been willing to wait (~5 min). presumably it isn't getting past single pass for some reason.

**Comment by kp-121** [comment]
I'm not able to replicate this, but I have added a progress bar to single pass and multi pass, so you can see if any progress is being made. This implementation is not perfect, but if it is something we decide to use going forward we can fix the minor bugs with it. I'll draft a release shortly.

**Comment by jack-elliott** [comment]
It is only occurring if I use videos I recorded on the phone apparently. With the progress bar (nice touch), it crashes after several seconds now.

**Comment by kp-121** [comment]
Interesting. Do you notice which step it is crashing on? Does it finish the single pass (or how far into the single pass does it get)?

**Comment by jack-elliott** [comment]
It stopped at single pass, about 50 (units) in on the progress bar

**Comment by kp-121** [comment]
That's not good. What is the resolution of the frames?

**Comment by jack-elliott** [comment]
2160x3840

**Comment by kp-121** [comment]
I'll try replicating with that size. I'm thinking it's an index error. It could be another memory error though.

**Comment by jack-elliott** [comment]
ok, Let me know when you want me to test it!

**Comment by kp-121** [comment]
Not able to replicate, reopen this if we run into this problem again.
