### ISSUE TITLE
Calibration informative popup

### ISSUE THREAD

**Issue by kp-121** [mI-PIV/app#201]
While we work on making the calibration use a video, we need to add a popup with a message: "Be sure to use the same camera settings and magnification as the videos you intend to conduct PIV on".

**Comment by jack-elliott** [comment]
This seems like an @Kevin-Jay-Roberts21  thing

**Comment by Kevin-Jay-Roberts21** [comment]
Do we want this popup message to show up after pressing the Create Camera Calibration tab? Then have the user close the message and proceed to Record Video or Pick A Video?

**Comment by jack-elliott** [comment]
Let's have this pop-up happen after the user selects "Create Camera Calibration" and before they can select "record video" a "pick a video". We should also say something to the effect of (but worded more clearly): try not to move the camera after you have taken your calibration images.

**Comment by Kevin-Jay-Roberts21** [comment]
Commit e521a73 fixes this issue.
