### ISSUE TITLE
Multipass and post processing indexing fix

### ISSUE THREAD

**Issue by jack-elliott** [mI-PIV/app#202]
Multipass and post-processed results are all 0 valued vectors. If more detail is needed I can describe what steps I took to get this, but it seems consistent across what I've tried.

**Comment by jack-elliott** [comment]
The progress bar for multipass is much faster than single pass, which doesn't make sense (the window size decrease isn't making that large of a difference) and may hint to the issue.

**Comment by kp-121** [comment]
PostProcessing and Multipass are lazily indexed, need to update the index to start at 0 and end on the edge with checks and padding.

**Comment by kp-121** [comment]
@jack-elliott The new indices fix works great, however I'm seeing those vector 'holes' again. What did we do to fix it last time?
