### ISSUE TITLE
User-defined images not processing

### ISSUE THREAD

**Issue by jack-elliott** [mI-PIV/app#203]
With all default parameters, the and a user defined video, the app is crashing during single pass processing.

**Comment by kp-121** [comment]
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 4218 (FinalizerDaemon), pid 8388 (piv.uploadmedia)

**Comment by kp-121** [comment]
https://stackoverflow.com/questions/55795041/how-to-solve-android-fatal-signal-11-sigsegv-code-1-fault-addr-0x0-in-tid-xx

**Comment by kp-121** [comment]
Okay, when we were copying the correlation matrix we were using an opencv function (clone) but as mentioned in the stackoverflow posted above we should use the opencv function (copyTo). I've changed that and also added boundary guards so we don't try to access out of bounds when removing the primary peak. I've tested on all fps at the highest resolutions without crashing. I'm not 100% confident this fixed it, but maybe @jack-elliott you can test this with tonight's release.

**Comment by kp-121** [comment]
#208 might have fixed this, but I'm going to keep it open until we have more testing to make sure.
