### ISSUE TITLE
Glossary Edit(s)

### ISSUE THREAD

**Issue by jack-elliott** [mI-PIV/app#205]
- [x] The laminar boundary layer equation in the fluids glossary: boundary layer is just the boundary layer image over again. Not sure when/how this changed but likely a simple fix for @Kevin-Jay-Roberts21 
- [x] The vorticity and circulation page final paragraph should say: The final results page allows the user to visualize and quantify the vorticity in their flow field by selecting Vorticity: Display. The sliders change what minimum/maximum value is displayed in the results. An example of a vortex ring mI-PIV result, marked by regions of high vorticity in the mI-PIV result, is shown here:
![Vorticity Screenshot](https://user-images.githubusercontent.com/77805273/144113179-9b9ee011-9556-4610-b705-0c1c06f246a7.jpg)
e 

- [x] in Wake:, after the current text, add: "or the flow moving behind a ball flying through the air, as shown here: "
- [x] in Shear: after the current content, add: "implications for mI-PIV: Visually, shear is the change in velocity across a certain distance. For example, the flow in the photo here changes from near zero velocity at the top and bottom, to high velocity in the center. These regions of high shear are highlighted by the vorticity (yellow and orange).  
![ShearExample Image](https://user-images.githubusercontent.com/77805273/144114596-2ef8c3aa-7378-4072-ac06-acf4dbf98eac.jpg)
Be careful! Since PIV averages the velocity over each interrogation region of flow, high shear can make the PIV less accurate. 

- [x] in External/Internal Flows: We will add a better image for the external flow, this is going to rely on the multipass being fixed, so standby

**Comment by jack-elliott** [comment]
Hey @Kevin-Jay-Roberts21, these seem like stuff to have you work on if you have time.

**Comment by jack-elliott** [comment]
![External](https://user-images.githubusercontent.com/77805273/156443342-24116902-e64e-4374-8766-6ab46e97ac0b.jpg)
Hey @Kevin-Jay-Roberts21 here's that external flow image (finally)

**Comment by Kevin-Jay-Roberts21** [comment]
Commit 0d76b69 closes this issue.
