### ISSUE TITLE
Image Pair Selection defaults

### ISSUE THREAD

**Issue by kp-121** [mI-PIV/app#220]
- [x] The second frame selection should have radio button options (+1, +2, +5) of the first frame selection.
- [x] Remove the second frame selection.

**Comment by jack-elliott** [comment]
We should discuss this before implementing @kp-121 since we just received some relevant feedback from the advisory board

**Comment by kp-121** [comment]
Radio group with different frame skipping options

**Comment by jack-elliott** [comment]
Sorry for the delay, 1,2,3,4 in my opinion
