### ISSUE TITLE
Video Processing

### ISSUE THREAD

**Issue by jack-elliott** [mI-PIV/app#226]
With our current processing as quick as it is, the advisory board suggested we add the ability to process full videos to provide videos of results.

**Comment by kp-121** [comment]
Just to be clear, the output will be a video of the vector fields? So this might have a video play page instead of the two-frame results page? Or is the thinking more of the two-frame results with maybe a temporal slider to change the viewed results?

**Comment by jack-elliott** [comment]
can we do the temporal slider and then export to a video?

**Comment by kp-121** [comment]
Absolutely. I'll start on that.

**Comment by kp-121** [comment]
Note to myself:

- [ ] Text output for each processed frame pair
