### ISSUE TITLE
Output .txt

### ISSUE THREAD

**Issue by jack-elliott** [mI-PIV/app#229]
We should put headers on the output .txt columns with units (i.e. pixels or cm) to make sure users know what they are looking at. Also, the x and y locations in the output should be in cm if a calibration has been applied (as of now they are still in pixels)

**Comment by kp-121** [comment]
- [ ] Add headers to output

The calibrated output should be saved like CENTIMETERS_SINGLEPASS_Experiment_4.txt 

Let me know if you're not seeing something similar to the picture beow with a calibrated experiment.

![image](https://user-images.githubusercontent.com/20914336/152073082-d5bed474-78ae-40f5-a576-07e8e4c14538.png)

**Comment by jack-elliott** [comment]
Yes, particularly the CENTIMETERS... looks new?

**Comment by kp-121** [comment]
The CENTIMETERS files are only created when you run a calibrated experiment.

**Comment by jack-elliott** [comment]
Right, and those results have the x and y in pixels, not cm still. Does that help?

**Comment by kp-121** [comment]
Mine have different measurements for the pixel output and cm output. Yours are the same?

**Comment by kp-121** [comment]
Nevermind, I just figured it out. I'll add it.
