### ISSUE TITLE
Saving Input Parameters

### ISSUE THREAD

**Issue by jack-elliott** [mI-PIV/app#237]
Let's let a user save processing parameters for easy selection in their future. To do this, I see either 1) letting them set defaults, or 2) letting them save then upload a set of parameters. @kp-121 , thoughts/which is easier to implement and we do that one?

**Comment by Kevin-Jay-Roberts21** [comment]
When a user clicks on the Input PIV Parameters button, the PIV Parameters Dialog pops up and all the inputs are already set to a default. Does that mean we can close this issue? @jack-elliott ? Or would you like for them to set their own personal default parameters?

**Comment by jack-elliott** [comment]
The request here is from users' experience, where if someone wants to
repeat a set of parameters other than the defaults, it becomes tedious.
Saving a user-prescribed set of parameters would be a good way to fix that,
so yes to the last part.

**Comment by Kevin-Jay-Roberts21** [comment]
What do you both think (@jack-elliott and @kp-121 ) about adding a checkbox inside the PIV Parameters popup where, if clicked, the user sets his/her own defaulted parameters? Also with a button added where, if clicked, the user can set their defaulted parameters?

**Comment by jack-elliott** [comment]
So my thought is that we add a checkbox in the advanced parameters, where the user can set what they have selected as the default. That might be easier than saving set(s) of parameters and allowing users to access them by name later. Then as Kevin said, allow the user to reset those parameters if desired to what we have prescribed as the default.

**Comment by kp-121** [comment]
That works for me. @Kevin-Jay-Roberts21 if you work on this, make sure that default parameters are handled in a separate class that is created in the parameter popup.

**Comment by jack-elliott** [comment]
Just to clarify, what I suggest would be easier for the **users**/more aligned with what they requested. Not trying to disagree with what Kris said!

**Comment by Kevin-Jay-Roberts21** [comment]
@jack-elliott, just so I'm on the same page, we add one checkbox where if checked, the parameters they've selected is their new default. And a button where if clicked, the parameters are set to the original default. Is that correct? And yeah @kp-121 will do on the separate class. You are mentioning the PivOptionsPopup.java class correct?

**Comment by kp-121** [comment]
@jack-elliott  No worries, we're talking about the same thing. I was thinking in backend terms (the app will have to save and load them) and not the user having to save and load by name.

**Comment by jack-elliott** [comment]
I would make the "set as default" (which makes whatever the users have entered at that time the default moving forward) a button, and the "reset default" *which reverts the default back to what we have) as a button. likely near the bottom of advanced parameters.

**Comment by Kevin-Jay-Roberts21** [comment]
@jack-elliott sounds good. I like this idea!

**Comment by kp-121** [comment]
@Kevin-Jay-Roberts21 That works. Also, just an FYI, the default class will only have to save and load a PivParameters class (which we are already doing for every experiment). Let me find where we are doing the saving/loading to send as an example.

**Comment by kp-121** [comment]
@Kevin-Jay-Roberts21 In Utilities folder you can find the FileIO class that handles writing and reading Java objects. You can check it out, but I think I'll write a couple of new methods specifically for the default parameters reading/writing that you can use.

https://github.com/mI-PIV/app/blob/5fe22618904460295d9c87879c80d97d1afb4729/app/src/main/java/com/onrpiv/uploadmedia/Utilities/FileIO.java#L33-L34

**Comment by Kevin-Jay-Roberts21** [comment]
@kp-121 Thank you! I'll get to it. I'll also be pushing my commits and branch to github early on so that you're able to check out my progress and make edits/comments if you need.

**Comment by kp-121** [comment]
@Kevin-Jay-Roberts21 I've pushed up the fixes for the user default parameters. Make sure to delete your old PivParameters.obj file on your phone (Android/data/com.ornpiv.uploadmedia/files/miPIV_{username}/) before running the fixes or you'll get an exception. I've done some minimal testing, but it seems to work. Feel free to test some more and then create a pull request that closes this issue and the one I created Wednesday.

**Comment by Kevin-Jay-Roberts21** [comment]
Hey Kris,

Excellent. I went ahead and started testing for different users and the
values are being saved accordingly, with the exception of fps. It just
resets to 20. Since this is calculated outside of PivParameters, should we
worry about setting a default value for it? If we do, how would we go about
this? Also, the radio checkboxes (Correlation method, Replace Missing
Vectors, Background Subtraction, etc.) are not being saved as defaults.
This may be a question for Jack, but do you think we want those radio
checkboxes to have the saving ability as well?

Thanks,

Kevin Roberts

**Comment by kp-121** [comment]
There is a ticket to refactor how we get/calculate FPS using the video's metadata, so that will be fixed in the future. We'll want to save those other parameter values, and that can be achieved by doing what we did with the GUI texts. Create a method that loops through checks the loaded parameter values and sets the radio buttons accordingly.

**Comment by kp-121** [comment]
Looking at it now, you'll just need to change lines 399-401 to the get the values from the 'parameters' variable instead of setting them with defaults.

**Comment by kp-121** [comment]
I pushed up the changes. Let me know if you notice anything else in your testing.

**Comment by Kevin-Jay-Roberts21** [comment]
Hey Kris,

Nice! I tested the radio buttons out and they're working just fine. I also
added saved defaults for the Background Subtraction radio group. I wasn't
sure how to write it in a clearer way, so I just wrote a small method at
the bottom of the PivOptionsPopup class that handles it. I tested it and
it's been working as I suspected. If you want to take a look at it I've
pushed the changes. If it's all the same to you I can go ahead and merge
the branch and close the issues. Just let me know!

Thanks,

Kevin Roberts

**Comment by kp-121** [comment]
Sounds good. Go ahead and create a pull request.

**Comment by Kevin-Jay-Roberts21** [comment]
Commit 6c04042 fixes this issue.

**Comment by kp-121** [comment]
#293
