### ISSUE TITLE
Pixel Phone Check Correlation Bug

### ISSUE THREAD

**Issue by jack-elliott** [mI-PIV/app#255]
On a Google pixel, in the experiment pathway, when a user goes through the “check image correlation” steps, the ability to select PIV parameters goes away. If the user does not select “check image correlation”, the ability to select PIV parameters etc. remains.

**Comment by kp-121** [comment]
I'm not able to replicate this on Pixel 3, 4 (emulators) or Galaxy. Correlation animation and PIV parameters popup should be completely independent of one another, but I'll check the code to make sure.

**Comment by jack-elliott** [comment]
How odd. I think the calibration is more important, but this was definitely a problem that didn't happen on my phone or the V40, but did happen on the pixel phone.

**Comment by kp-121** [comment]
The only thing I found was some bad logic that could have possibly caused a gui crash. I've corrected the logic, but I'll keep this open until we know that was the issue.

**Comment by Kevin-Jay-Roberts21** [comment]
Just to add here: I tested this on my Google Pixel 4 and didn't run into any errors. The ability to select PIV parameters remained for me.

**Comment by kp-121** [comment]
We haven't seen an issue. Someone can open back up if they notice anything.
