### ISSUE TITLE
Calibration

### ISSUE THREAD

**Issue by jack-elliott** [mI-PIV/app#256]
The calibration is giving values which are much too large ~100x true.

**Comment by kp-121** [comment]
Please double check the math:
https://github.com/mI-PIV/app/blob/02a15f2d2215bef9e760385675f71adbfb0d7f54/app/src/main/java/com/onrpiv/uploadmedia/pivFunctions/PivResultData.java#L204-L209

**Comment by kp-121** [comment]
This is really the only control we have over the calibration. If the calibration pattern isn't on a 8 x 11 paper then the calibration ratio will be off.

**Comment by jack-elliott** [comment]
The pattern was on the right scale sheet, If I understand the way the
variable is written correctly, the pixel/physical ratio should be a divisor
(not a multiplier: line 204ish) . We should also just get an example we
like and step through this to check as well. is that something we can do
Monday?

**Comment by kp-121** [comment]
Yep, we can work on it on Monday. I'll add all the calibration code snippets here for easy access.

https://github.com/mI-PIV/app/blob/02a15f2d2215bef9e760385675f71adbfb0d7f54/app/src/main/java/com/onrpiv/uploadmedia/Utilities/Camera/Calibration/CameraCalibration.java#L26

https://github.com/mI-PIV/app/blob/02a15f2d2215bef9e760385675f71adbfb0d7f54/app/src/main/java/com/onrpiv/uploadmedia/Utilities/Camera/Calibration/CameraCalibration.java#L170-L172

**Comment by kp-121** [comment]
Calibration now takes user input. See #264
