### ISSUE TITLE
Advanced parameters popup gui

### ISSUE THREAD

**Issue by kp-121** [mI-PIV/app#272]
The advanced parameters popup GUI needs reworked. The elements are being cropped.

**Comment by Kevin-Jay-Roberts21** [comment]
Simplest fix to this would be to increase/decrease the size of the alert dialog when the advanced parameters checkbox is clicked. Another solution would be to decrease text size of the elements in the window or "scooch" all of the lightbulbs to the left which would require refactoring the LightBulb class. I went with just simply increasing and decreasing the window size.

**Comment by Kevin-Jay-Roberts21** [comment]
Commit 3b646df fixes this issue.

**Comment by kp-121** [comment]
I'm going to make this an activity rather than a popup. This will make sure nothing gets cropped.
