### ISSUE TITLE
Frame selection has frames from different frame sets

### ISSUE THREAD

**Issue by kp-121** [mI-PIV/app#291]
When working with multiple frame sets, frame selection either previews the wrong frame set or allows users to select frames from a different frame set.

**Comment by kp-121** [comment]
- [ ] Selecting frames will show different frame set images
- [ ] Alphabetically sort the frame sets when loading into  spinner

**Comment by kp-121** [comment]
@jack-elliott I can't replicate, but I think I know what the problem is. The frames directory already existed and it allowed you to overwrite a certain amount of the frames, but all the frames it didn't overwrite were left. You can check this by deleting your user data, then creating the two frame sets again. Sorry, I know it's annoying to delete all the data and create it again.

**Comment by jack-elliott** [comment]
That is kind of what I thought and tried yesterday. I can play around with
it some more and try to replicate. Shouldn't this go away when we fix the
naming issue?

**Comment by kp-121** [comment]
That's what I was thinking. I pushed in the naming issue this morning, so I'll close this and we can always open it back up.
