### ISSUE TITLE
Results processing bug

### ISSUE THREAD

**Issue by Zainghgh** [mI-PIV/app#296]
Whenever we Select Multipass under processing section in any parameter combination it Jump Back to Compute PIV or mI-Piv App Stop working.

**Comment by kp-121** [comment]
I'm not able to replicate this bug. Does it crash when you select multipass or when you hit 'Apply'?

**Comment by Zainghgh** [comment]
Yes, it crashes and sometimes it jump back to compute PIV.

**Comment by kp-121** [comment]
Does it crash when you press on 'Multipass' or when you press 'Apply Changes' button after selecting multipass?

**Comment by Zainghgh** [comment]
mI-PIV app crashes after I press apply changes button after selecting
multipass.

**Comment by kp-121** [comment]
Thanks, that let's me know it's a backend issue and not a gui issue. I released a new update this afternoon, can you check if the bug is still present?

**Comment by Zainghgh** [comment]
Ok thank you for the update .I will let you know if the issue persists.
