### ISSUE TITLE
Default Parameters Not saving

### ISSUE THREAD

**Issue by jack-elliott** [mI-PIV/app#326]
"Setting" a new set of default parameters does not actually do so.

**Comment by Kevin-Jay-Roberts21** [comment]
After testing this on my phone, for me, the all the parameters are being set to the correct default parameter after hitting the Set button except the Frames/Second (FPS) and the Negative Filter.

**Comment by kp-121** [comment]
- [ ] Add negative filter bool to the default parameter loading
- [ ] Fix the FPS parameter loading
- [ ] #312

**Comment by jack-elliott** [comment]
Whether or not the meta data consistently describes the true time
(neglecting edited videos with frame rate adjusted), I could see users
getting video from elsewhere as well. I think we should continue to allow
users the ability to change this if they are confident enough to do so. As
a result, we should make it "settable" through setting new defaults. My
thoughts at least.

**Comment by Kevin-Jay-Roberts21** [comment]
What about having the user be able to set a fps default value, but give them a warning depending on the image set they select? For example, if they select an image set that generated a fps value of 15, but their default is set to 120 fps, then upon clicking the Input PIV Parameters button, we show a quick popup saying that their defaulted fps value is unreasonably high for the image set they selected. What do you think?

**Comment by jack-elliott** [comment]
I just looked into this (checked on my phone as well), the metadata is playback speed. This means that it does not consistently represent the recorded framerate (e.g., my slow-mo plays back at 30 fps even if it is recorded at 120fps). So, we should not rely on the meta-data at all imo (it will almost always just say 30 fps). For this issue then, let's let users pick and maintain a default of their choosing. This seems more ok to me, in the sense that if the user picks a framerate which is wrong, but cares/knows enough to specify framerate and spatial calibration, then they will likely see that their answers are off by some constant factor from the true result (even the high school curriculum will have the correct answer. Further, with the meta-data not being reliable, we don't have a way to check for extreme values anyways. Let me know if you/ya'll agree/disagree.

**Comment by kp-121** [comment]
Ah, that's very good to know. I agree and will add FPS to the user default parameters. (Side note, I'll see if it's possible to extract the real FPS not playback speed for #312 )

**Comment by jack-elliott** [comment]
Yes it does
