### ISSUE TITLE
Results Page Information Clarity

### ISSUE THREAD

**Issue by jack-elliott** [mI-PIV/app#327]
The results page: information tab should be reformatted to include:
(in bold) Velocity:
the velocity magnitude
x and y position (in cm if applicable)
(in bold) Other
everything else we already display

**Comment by kp-121** [comment]
We might want to think about a more structured view of the information, rather than just a string output.

**Comment by Kevin-Jay-Roberts21** [comment]
When you say Velocity @jack-elliott, do you just mean U and V? And their magnitudes? If not, how might we go about computing Velocity @kp-121? Thanks!

**Comment by kp-121** [comment]
The PivResultData data structure keeps all the magnitude values, so you can just grab the magnitude from that using the interrogation region coordinates. As for Jack's first comment, I believe he wants something that looks like this: 

**Velocity:**  magnitude
pixel_x, pixel_y  (or if calibrated, cm_x, cm_y)
**Other:**
vorticity
u, v
conversion factors (if calibrated)

**Comment by Kevin-Jay-Roberts21** [comment]
@kp-121 when I call pivCorr.getMag() to get the magnitude, I get a weird value, something like "[[D@2d37336". Could you help describe how to use the interrogation regions to get the magnitude from pivCorr? Just want to make sure I'm getting the correct velocity magnitude. Thanks!

**Comment by kp-121** [comment]
Yep, the magnitudes are setup in a 2D array. So you'll need to do something like "pivCorr.getMag()[y][x]" to access that magnitude value. Look at ViewResultsActivity lines 756, 757, and 759 for a reference.

**Comment by Kevin-Jay-Roberts21** [comment]
Excellent! That's what my guess was. Thanks!

**Comment by Kevin-Jay-Roberts21** [comment]
Commit 82f6a3f fixes this issue.

**Comment by jack-elliott** [comment]
Hey Kevin, No I am hoping for magnitude (i.e. (u**2+v**2)**0.5)
