### ISSUE TITLE
App Crash in Processing

### ISSUE THREAD

**Issue by jack-elliott** [mI-PIV/app#331]
The only difference between normal processing and here is that I selected "view background" when I generated the frames. I am not entering anything aside from defaults in the advanced parameters section (meaning the background subtraction shouldn't be running). This leads to a crash during processing.

**Comment by kp-121** [comment]
I can't replicate, can you send me the video? Also, is this on 0.18 or 0.17?

**Comment by jack-elliott** [comment]
I emailed it to you (avoid file size issues). This was on v0.17

**Comment by kp-121** [comment]
java.lang.ArrayIndexOutOfBoundsException: length=66; index=66
        at com.onrpiv.uploadmedia.pivFunctions.PivFunctions.getCubicInterpolation_v(PivFunctions.java:1084)
