### ISSUE TITLE
Play Store Listing

### ISSUE THREAD

**Issue by kp-121** [mI-PIV/app#336]
- [x] Resize Icon
- [x] Resize screenshots
- [x] Upload to play store console

**Comment by kp-121** [comment]
[screenshots&icon.zip](https://github.com/mI-PIV/app/files/9245680/screenshots.icon.zip)

**Comment by kp-121** [comment]
Let me know if you don't have access to the play store console. 
https://play.google.com/console

**Comment by Kevin-Jay-Roberts21** [comment]
Icon and screenshots have been resized accordingly and uploaded to the play store.
