### ISSUE TITLE
Processing on Locked Screen

### ISSUE THREAD

**Issue by jack-elliott** [mI-PIV/app#338]
Processing seems to end when the phone screen get locked/sleeps. This becomes an issue now that we have multiple image processing.

**Comment by kp-121** [comment]
onRestoreInstanceState in ImageActivity:
- [ ] Re-attach work thread
- [ ] Continue progress dialog

**Comment by kp-121** [comment]
https://developer.android.com/training/scheduling/wakelock#cpu
