### ISSUE TITLE
Potential Bug on Whole Set Processing

### ISSUE THREAD

**Issue by jack-elliott** [mI-PIV/app#339]
I ran whole set processing on a series of images, and the results for image 13 to image 14 were exactly twice the displacement of all the other image pairs (all others were correct). This tells me somewhere that an image was skipped (i.e., it actually processed image 13 to 15 or image 12 to 14). Any thoughts on what could cause this @kp-121 ?

**Comment by kp-121** [comment]
I'm not sure. It could be the frame extractor is creating a double frame image, more likely is a path issue when loading the frames. I'll take a look.

**Comment by jack-elliott** [comment]
I ran a single image pair test and ran into this issue as well on the newest release. Can we put this as the highest priority issue @kp-121?
