### ISSUE TITLE
Results maximize

### ISSUE THREAD

**Issue by kp-121** [mI-PIV/app#342]
- [ ] ability to maximize/minimize results image stack
- [ ] New Maximized gui 
- [ ] Info window on selection ( transparent )
- [ ] Temporal slider hiding

**Comment by jack-elliott** [comment]
So rotating the screen at the results page causes a crash. While the above issues may be improvement, the crash specifically should be dealt with as a bug imo.

**Comment by kp-121** [comment]
I'm might have fixed this. @jack-elliott could you check this and make sure. I'll watch the crash reports.

**Comment by jack-elliott** [comment]
this is now working

**Comment by jack-elliott** [comment]
However, when the phone is rotated, it re-displays the save location
dialogue and seems to reset some parameters (vector scale included)

**Comment by kp-121** [comment]
I noticed that as well. I'll make a ticket.
