### ISSUE TITLE
Information Selection Crash (only when loading an experiment)

### ISSUE THREAD

**Issue by Kevin-Jay-Roberts21** [mI-PIV/app#351]
Upon creating an experiment, when a user goes through the whole process and gets all the way to the Results page, there is no issue when tapping on the graph. However, when a user loads an experiment, when tapping on the graph in the results page, the app crashes. The error message is the following:

Attempt to invoke virtual method 'double[][] com.onrpiv.uploadmedia.pivFunctions.PivResultData.getVorticityValues()' on a null object reference

The error occurs (on line 805 of ViewResultsActivity.java) because multipass is null and tries to call .getVorticityValues(). Again, this happens only when loading an experiment.

**Comment by kp-121** [comment]
Good error report. This means we're not loading the multipass object file correctly. I'll have a fix shortly.
