### ISSUE TITLE
Calibration Default not Saving

### ISSUE THREAD

**Issue by jack-elliott** [mI-PIV/app#357]
On a samsung A51 selecting a calibration then choosing "set as default" does not save, and I need to re-select the calibration each time.

- [x] Write checks to make sure we are writing and loading the user parameter file correctly.

**Comment by kp-121** [comment]
The new release (0.23) has logging in place to tell us if there is a problem with saving or loading the user default parameters file. @jack-elliott when you get a chance, try to save and load the default parameters, and hopefully I'll be able to see what the issue is.

**Comment by jack-elliott** [comment]
Ok I ran it, let me know if you can/can't see it.

**Comment by kp-121** [comment]
Nope. It's not there. I'm going to have to step through the code with your phone in person. We can have our Monday meeting in Prof. K's lab if that works for you @jack-elliott?

**Comment by jack-elliott** [comment]
I think this week we are including Dr. Minichiello in the meeting. The rest
of Monday is also rough for me this week. How about Tuesday any time before
12?

**Comment by kp-121** [comment]
Tuesday at 10?

**Comment by jack-elliott** [comment]
Perfect

**Comment by kp-121** [comment]
Calibration!!!!
