### ISSUE TITLE
Output Video

### ISSUE THREAD

**Issue by jack-elliott** [mI-PIV/app#359]
When user is doing whole set processing then outputting a video to gallery, the resulting video has a hard time playing in the phone or when downloaded to a computer. Also, the output framerate seems slow.

- [x] User selected fps
- [ ] Make mp4 conversion more robust (check what type of errors/video corruption ffmpeg will output)

Here's an example

https://user-images.githubusercontent.com/77805273/184225598-06952c82-f054-4ef6-bdff-df8f6cfa2dfe.mp4

**Comment by kp-121** [comment]
I thought it would be better to see the vector field changes so I set it to 2 FPS. I can change it to 30 fps, or even have a popup giving the user the option of output fps.

 I spent a lot of time with the format, and android's playback formats are finicky. I'll try to see if we can't find which formats the user's phone allows then convert it.

**Comment by jack-elliott** [comment]
Ah that makes sense. Maybe a user-defining option for the framerate would be best then. Opening the video took some effort on the phone, and I can't get it open on the computer. I think opening the vids on both is ideal.

**Comment by kp-121** [comment]
I went with MP4 because that's the most popular format and can be played on most devices, but I'll double check that the format conversion isn't corrupting the video.

**Comment by kp-121** [comment]
https://user-images.githubusercontent.com/20914336/184687754-bba03cc5-e017-4db5-87a2-5da40f48a9ff.mp4
