### ISSUE TITLE
Background Subtraction

### ISSUE THREAD

**Issue by kp-121** [mI-PIV/app#39]
We might need to implement background subtraction into our PIV algorithm. I will create a branch that implements this and then we can merge the branch without problems.

**Comment by kp-121** [comment]
@jack-elliott I have the background subtraction working. I'm just curious if we need to put a check box in the frame generation options for background subtraction, or do we want to always do apply background subtraction?

**Comment by jack-elliott** [comment]
I guess if we generate the "static" background using the floor values across the generated images, it would be good then to ask if the user wants to generate the static background (during frame generation) then maybe displaying it at some point after (potentially right after frame generation. However, for actually using that static background and/or the method in the paper you sent me, we should provide the user the option in the PIV parameters menu under advanced settings. With the default being to do so with the paper method.

**Comment by kp-121** [comment]
That sounds good. I'll start working on the paper method and the menu items. I'll upload some of the results so you can see them. They're pretty neat.

**Comment by kp-121** [comment]
![BACKGROUND](https://user-images.githubusercontent.com/20914336/134558752-a11b9f36-bf8a-4e00-a549-d017a167c51c.jpg)
Background

**Comment by kp-121** [comment]
![EXTRACT_2021_09_23_11_41_019](https://user-images.githubusercontent.com/20914336/134558804-919d77f7-530f-41e5-981d-8954e1d421b9.jpg
![EXTRACT_2021_09_23_11_41_005](https://user-images.githubusercontent.com/20914336/134558818-68c8138c-c1ce-41bd-9a0a-e8d217e7e281.jpg)
)
Frames with the background subtracted

**Comment by jack-elliott** [comment]
These look great!

**Comment by kp-121** [comment]
#155 adds in the two different types of background subtraction. They both work great, however we're getting some wild vector fields. I'm going to leave this ticket open until we can figure out why we're getting bad results.

**Comment by jack-elliott** [comment]
Are the wild results in the regions with very little particle movement?

**Comment by kp-121** [comment]
They are wild everywhere. I'll upload them here.

**Comment by kp-121** [comment]
![TEST1__Experiment_4](https://user-images.githubusercontent.com/20914336/134599260-8f67357d-837c-4ff0-95c5-a60670c6bf02.png)
Frame 1 using the two-frame background subtraction.

![TEST2__Experiment_4](https://user-images.githubusercontent.com/20914336/134599279-691e219e-cc3c-4adf-aa94-aa930fe172a4.png)
Frame 2 using the two-frame background subtraction.

**Comment by kp-121** [comment]
![Saved_Image_2](https://user-images.githubusercontent.com/20914336/134599329-578ee1b3-dd9d-4690-bf86-f0d37fcef5cc.png)
Vector field.
![Saved_Image_0](https://user-images.githubusercontent.com/20914336/134599348-39c42d45-9827-4ff8-a9fb-a61d3380cc57.png)
Vector field with vorticity.

**Comment by jack-elliott** [comment]
it looks like most of the particles were removed. These are from the videos I sent on google drive today? If so which ones?

**Comment by kp-121** [comment]
These are not from any of those videos. I'll run a new experiment with one of those real quick.

**Comment by jack-elliott** [comment]
Ok, Some of the weirdness is likely to reoccur. We are going to get interesting results where the background subtraction removes too much of the image (where the pipe is in these), where the particles aren't moving much (the quiescent region), and where the streaks just fill the images up with noise. Which are the three regions of bad particles in the results above. Hopefully the better videos do better, especially using the floor removal method for those (where only the pipe will leave a bad region).

**Comment by kp-121** [comment]
I just found a weird bug trying to use the 30mlwater video. I keep getting permission denied, so I'll add that to the list. It will be on tomorrow's release, so maybe you might have better luck. I'll keep trying and if I can get it to work I'll post the results here.

**Comment by jack-elliott** [comment]
Ok, I used it in the current release so I'll try again tomorrow and make sure. it looks like the issues are all where issues would be expected as described above. Did you try the videos from above with the floor removal one? I think the subtraction method is going to be rough when there are large regions of quiescent fluid and noise without masking available.

**Comment by kp-121** [comment]
Much better results with the 30ml video. You're right, the bad vectors are where there aren't very many particles.

![FRAME1__Experiment_4](https://user-images.githubusercontent.com/20914336/134601882-4901a928-8b6b-4b54-86da-c8ce7a856d80.png)
Frame 1

![FRAME2__Experiment_4](https://user-images.githubusercontent.com/20914336/134601901-daab3d61-e89f-4845-a078-db5068758051.png)
Frame 2

![Saved_Image_0](https://user-images.githubusercontent.com/20914336/134601928-b888491f-5fdf-4ab6-8df8-c02a03d8203f.png)
Vector field

![Saved_Image_1](https://user-images.githubusercontent.com/20914336/134601940-2b361ba7-6b0d-4327-9e93-cb3b33e6ea47.png)
Vector field with vorticity.

**Comment by jack-elliott** [comment]
Those look great! I added a issue regarding geometric masks. It's not pressing at all but I think that would be the best method to get around large regions we know will be bad like that.

**Comment by jack-elliott** [comment]
The Background subtraction is working well on my phone (including no permission issues with the google drive videos). However, I think part of why we would run into issues is that the implementation is a bit different from usual methods (only run one method, and select either in processing selection). I think when the frames are generated we should be asking if the user would like to generate a background (but not yet allow them to apply it at this stage). Then, when the user is selecting parameters, we should allow them to select either the floor background or the subtraction background, but not both. Finally, we should allow the user to preview the generated background (not background subtracted frames) in frame generation, and provide the user the option to select the raw images or background subtracted images in the results page. That's a lot sorry!

**Comment by kp-121** [comment]
That makes sense and I think this will reduce confusion on the two types of background subtraction. This won't be too difficult to implement since all the background subtraction methods are written and I think we can get the changes in for next week's release.

**Comment by kp-121** [comment]
- [ ] Allow user to see background in frame extraction page (we can just change the checkbox)
- [ ] Change checkbox to a radio button to PIV parameter popup with the types of background subtraction
- [ ] Radio widget logic in PIVRunner
- [ ] Save background subtracted frames for results page viewing
- [ ] Add background subtracted frames radio button to background section of results page (only show if BS is selected)

**Comment by jack-elliott** [comment]
I like these, we should also be sure to include that the user has the option not to subtract a background if desired.
