### ISSUE TITLE
Whole Set Processing Frames 1&2

### ISSUE THREAD

**Issue by jack-elliott** [mI-PIV/app#394]
IN whole set processing frames 1 and 2 give ~ 0's. May be the autocorrelations (same images)

**Comment by kp-121** [comment]
@jack-elliott I'm not able to replicate this. Is it possible the frame set was created before we had fixed the frame name bug and it was overriding other files?
![6t5wip](https://user-images.githubusercontent.com/20914336/189769057-d6a1dd0d-4ffe-4999-a07a-947b7e3cb7fd.gif)

**Comment by jack-elliott** [comment]
I can't tell now if it is the odd frame set issue or if the first pair isn't working properly due to a unique issue. I can test once a release with the indices working is out?

**Comment by kp-121** [comment]
I did find an off-by-one issue when we're selecting the first frame, but I don't think that would affect the whole set processing. I'll leave the debugging video here if you want to use it with the next release. I'll keep looking at other frame sets to make sure though.

[debugFrameVid.zip](https://github.com/mI-PIV/app/files/9552313/debugFrameVid.zip)

**Comment by kp-121** [comment]
I'm assuming this was the same issue as #403 with the high speed capture. We can always open this issue again if we see the same problem.
