### ISSUE TITLE
Frame ordering

### ISSUE THREAD

**Issue by kp-121** [mI-PIV/app#398]
I've changed how we name the extracted frames, but the old timestamp ordering should've worked. I'm going to leave this open until we either find out why the ordering is off or we don't see the problem any more.

**Comment by jack-elliott** [comment]
OK, after doing another REALLY long one the first pair (frames 1&2) seem
wrong (maybe replicated frames). After that, they seem reasonable.

**Comment by kp-121** [comment]
It's most likely replicated frames caused by converting 1-based to 0-based and back again. This helps a lot!
