### ISSUE TITLE
Processing Indices

### ISSUE THREAD

**Issue by jack-elliott** [mI-PIV/app#403]
Selecting +1 default doesn't give new image, likely the same image twice (preview shows the same image).

**Comment by jack-elliott** [comment]
This changes according to which image is selected as the first frame

**Comment by kp-121** [comment]
Just the +<odd> selections

**Comment by kp-121** [comment]
@jack-elliott I'm not able to replicate this issue as well.

https://user-images.githubusercontent.com/20914336/189770082-d725a7b4-6715-414c-8115-0d70225c2355.mp4

**Comment by kp-121** [comment]
Disregard the last comment. That video actually showed us what is wrong. When the user selects the first frame ('1') it should be the '0' frame not the '1' frame.

**Comment by jack-elliott** [comment]
Here's an example of (potentially) the result of this, where every other image pair result is all zeros

https://user-images.githubusercontent.com/77805273/189815708-365aa542-e351-4053-9583-c73cb2c41958.mp4

**Comment by kp-121** [comment]
Is this happening with all videos or just one? I'm thinking this is a bad frame set. Below are the log outputs of a couple of whole set processing with the frame filenames.

<details>
  <summary>
    Sample Rate +1 Log
  </summary>
D/SET_PIV: Frame1: frame0001.jpg
    Frame2: frame0002.jpg

D/SET_PIV: Frame1: frame0002.jpg
    Frame2: frame0003.jpg

D/SET_PIV: Frame1: frame0003.jpg
    Frame2: frame0004.jpg

D/SET_PIV: Frame1: frame0004.jpg
    Frame2: frame0005.jpg

D/SET_PIV: Frame1: frame0005.jpg
    Frame2: frame0006.jpg

D/SET_PIV: Frame1: frame0006.jpg
    Frame2: frame0007.jpg

D/SET_PIV: Frame1: frame0007.jpg
    Frame2: frame0008.jpg

D/SET_PIV: Frame1: frame0008.jpg
    Frame2: frame0009.jpg

D/SET_PIV: Frame1: frame0009.jpg
    Frame2: frame0010.jpg

D/SET_PIV: Frame1: frame0010.jpg
    Frame2: frame0011.jpg

D/SET_PIV: Frame1: frame0011.jpg
    Frame2: frame0012.jpg

D/SET_PIV: Frame1: frame0012.jpg
    Frame2: frame0013.jpg

D/SET_PIV: Frame1: frame0013.jpg
    Frame2: frame0014.jpg

D/SET_PIV: Frame1: frame0014.jpg
    Frame2: frame0015.jpg

D/SET_PIV: Frame1: frame0015.jpg
    Frame2: frame0016.jpg

D/SET_PIV: Frame1: frame0016.jpg
    Frame2: frame0017.jpg

D/SET_PIV: Frame1: frame0017.jpg
    Frame2: frame0018.jpg

D/SET_PIV: Frame1: frame0018.jpg
    Frame2: frame0019.jpg

D/SET_PIV: Frame1: frame0019.jpg
    Frame2: frame0020.jpg

D/SET_PIV: Frame1: frame0020.jpg
    Frame2: frame0021.jpg

D/SET_PIV: Frame1: frame0021.jpg
    Frame2: frame0022.jpg

D/SET_PIV: Frame1: frame0022.jpg
    Frame2: frame0023.jpg

D/SET_PIV: Frame1: frame0023.jpg
    Frame2: frame0024.jpg

D/SET_PIV: Frame1: frame0024.jpg
    Frame2: frame0025.jpg
</details>

<details>
  <summary>
    Sample Rate +3 Log
  </summary>
 D/SET_PIV: Frame1: frame0001.jpg
    Frame2: frame0004.jpg

D/SET_PIV: Frame1: frame0004.jpg
    Frame2: frame0007.jpg

D/SET_PIV: Frame1: frame0007.jpg
    Frame2: frame0010.jpg

D/SET_PIV: Frame1: frame0010.jpg
    Frame2: frame0013.jpg

D/SET_PIV: Frame1: frame0013.jpg
    Frame2: frame0016.jpg

D/SET_PIV: Frame1: frame0016.jpg
    Frame2: frame0019.jpg

D/SET_PIV: Frame1: frame0019.jpg
    Frame2: frame0022.jpg

D/SET_PIV: Frame1: frame0022.jpg
    Frame2: frame0025.jpg
</details>
 
There is the possibility we aren't displaying the results in the correct order. I'll take a look at that.

**Comment by jack-elliott** [comment]
This is an issue with the "super-slow" motion video mode in my phone. For some reason segments of the videos in this mode are the same frame twice! Sorry for the trouble, never would have guessed that was the issue.
