### ISSUE TITLE
the link to the video is wrong

### ISSUE THREAD

**Issue by alexlib** [mI-PIV/app#420]
https://github.com/mI-PIV/app/raw/readme/resources/installGithubAPK.mp4 

[]([](https://github.com/mI-PIV/app/raw/resources/installGithubAPK.mp4))

**Comment by alexlib** [comment]
https://github.com/mI-PIV/app/raw/main/resources/installGithubAPK.mp4

**Comment by kp-121** [comment]
Thank you! The link has been fixed.
