### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by Kevin-Jay-Roberts21** [mI-PIV/app#5]
Spacing between groups of text and images are too large. Some of the images themselves are also too large. This is a common issue throughout the LEARN ABOUT FLUIDS and LEARN ABOUT PIV part of the app. 

Another issue of formatting is the scroll bar; it's covering some of the text and it needs to be moved out of the way and further off to the side.

**Comment by kp-121** [comment]
Pull request #12 fixes this
