### ISSUE TITLE
Interactive results page

### ISSUE THREAD

**Issue by kp-121** [mI-PIV/app#50]
More info to follow

**Comment by kp-121** [comment]
Pull request #63 added some interactivity to results page. However, I'm leaving this issue open for recommendations/suggestions for more interactivity with the results page.

One recommendation that I'll work on in the future is to display vector values instead of arrows on touch and/or toggle.

**Comment by kp-121** [comment]
Pathlines and streaklines might be a valuable visualization to implement.

**Comment by jack-elliott** [comment]
Seems like the actionable aspect of this one is done (interactive result vector value display) So this is getting closed w/o addition to the excel sheet (which likely replaces the intent of this issue).
