### ISSUE TITLE
Use a slider for frame selection instead of input

### ISSUE THREAD

**Issue by kp-121** [mI-PIV/app#84]
A slider is more mobile-friendly and it will allow the user to quickly compare the difference between frames. It will also help clean up user input checking.

**Comment by jack-elliott** [comment]
The slider works well until the user has a very long video, and the minimum distance results in very large number of frames generated. Could we add a text entry if the user desires as well?

**Comment by kp-121** [comment]
That's a very good point. We can keep the text input and have a slider underneath that changes the text input. Best of both worlds.

**Comment by jack-elliott** [comment]
That's what I was thinking, glad it sounds good to you too!

**Comment by kp-121** [comment]
#133 adds the sliders
