### ISSUE TITLE
App is exceeding Android memory limit

### ISSUE THREAD

**Issue by jack-elliott** [mI-PIV/app#98]
On a Google Pixel 4, for certain image pairs the "view results" button is leading to the start a new experiment-entering username.

**Comment by kp-121** [comment]
This usually means an exception was thrown while moving to the display results activity. I'll take a look.

**Comment by kp-121** [comment]
@jack-elliott When you have a moment, could you email me the two frames that caused this?

**Comment by kp-121** [comment]
This is just a note to myself. Getting memory errors. Could possibly be a [known problem](https://source.android.com/devices/tech/debug/native-crash#xom) with Android 10, and/or the size of the frames. I noticed these frames are substantially larger than other PIV videos.

**Comment by kp-121** [comment]
Android sets a memory limit for apps, and we are hitting that limit when calculating PIV with a frame size of 3820 x 2160. A quick fix would be to resize the frames before PIV, however I'll try to improve the PIV [memory performance](https://developer.android.com/topic/performance/memory) so we can keep the large frame resolutions.

**Comment by kp-121** [comment]
#106 will resize frames during extraction from videos. I'm considering this a temporary fix while I work on PIV memory optimization. Issue #105 will follow the memory optimization work. 

@jack-elliott This fix will go into the next release (Friday 28MAY2021), let me know if you need it sooner and I can create a manual release. Also, you'll have to extract the frames from the video again for this fix to work.

**Comment by jack-elliott** [comment]
We will keep this in mind moving forward-selecting image resolution. What is the resized resolution? The timeline works great. Thank you

**Comment by kp-121** [comment]
Right now the width is set at 1080 and the height is adjusted to keep the aspect ratio.

**Comment by kp-121** [comment]
I found OpenCV's native Mat objects need to be released for the Java garbage collector to free the memory. Essentially, not releasing these Mat objects was causing a memory leak. @jack-elliott This was a very, very good bug to find, and I should have the fix in for tomorrow's release (including removing the frame resizing).
